"""
MUMO — electronic structure (HOMO / LUMO) via GFN2-xTB.

WHY THIS AND NOT MD
-------------------
Mowriss asked for molecular dynamics inside 10-15 minutes plus HOMO/LUMO in the
report. The MD half is not achievable on this hardware: measured on the free
2-vCPU Space, trajectory MD runs at ~1 ns/day, so ten minutes buys roughly 8
picoseconds — not a simulation anyone can stand behind. HOMO/LUMO is the
opposite: seconds per molecule, and genuinely informative.

WHY xtb, AND WHY IT IS SAFE HERE
--------------------------------
Adding openmm to the shared conda environment segfaulted ProLIF and took the
whole Space down (exit 139, 2026-07-12). The lesson was not "avoid science", it
was "avoid native libraries that share a process with the rest of the stack".

xtb is a COMMAND-LINE EXECUTABLE, not a Python extension module. It is invoked
as a subprocess, its output is parsed as text, and nothing from it is ever
loaded into this interpreter — so it carries none of the ABI risk that openmm
did. The pattern is exactly how MUMO already runs AutoDock Vina.

REFUSING TO GUESS
-----------------
If the output cannot be parsed, this returns an error rather than a plausible
number. A wrong HOMO/LUMO that looks reasonable is far more damaging than a
missing one, because nothing downstream would flag it.
"""

import os
import re
import shutil
import subprocess
import tempfile

# Hartree -> electronvolt, CODATA
EH_TO_EV = 27.211386245988


def xtb_path():
    """Where xtb lives, or "" if it is not installed."""
    return os.environ.get("MUMO_XTB") or shutil.which("xtb") or ""


def xtb_available():
    return bool(xtb_path())


# The feature flag. Off unless the binary is actually present, so a build that
# lacks xtb simply does not offer the feature rather than failing at use time.
QM_AVAILABLE = xtb_available()


def prepare_xyz(smiles, seed=42):
    """SMILES -> optimised 3D geometry as XYZ text.

    xtb needs coordinates, not a graph. RDKit embeds and MMFF-optimises first
    so xtb starts from something sane; a bad starting geometry makes the SCF
    slow to converge or converge somewhere silly.
    """
    from rdkit import Chem
    from rdkit.Chem import AllChem

    mol = Chem.MolFromSmiles((smiles or "").strip())
    if mol is None:
        raise ValueError(f"Could not read that structure: {smiles!r}")
    mol = Chem.AddHs(mol)
    if AllChem.EmbedMolecule(mol, randomSeed=seed) != 0:
        raise ValueError("Could not generate a 3D conformer for this molecule.")
    try:
        AllChem.MMFFOptimizeMolecule(mol)
    except Exception:
        pass                                   # xtb will optimise anyway

    conf = mol.GetConformer()
    lines = [str(mol.GetNumAtoms()), "generated by MUMO"]
    for atom in mol.GetAtoms():
        p = conf.GetAtomPosition(atom.GetIdx())
        lines.append(f"{atom.GetSymbol():<3}{p.x:>14.8f}{p.y:>14.8f}{p.z:>14.8f}")
    return "\n".join(lines) + "\n", mol.GetNumAtoms()


_HOMO = re.compile(r"^\s*\d+\s+[\d.]+\s+(-?[\d.]+)\s+(-?[\d.]+)\s*\(HOMO\)", re.M)
_LUMO = re.compile(r"^\s*\d+\s+(-?[\d.]+)\s+(-?[\d.]+)\s*\(LUMO\)", re.M)
_GAP = re.compile(r"HL-Gap\s+(-?[\d.]+)\s*Eh\s+(-?[\d.]+)\s*eV", re.I)
_DIPOLE = re.compile(r"^\s*full:\s+\S+\s+\S+\s+\S+\s+([\d.]+)", re.M)
_ENERGY = re.compile(r"TOTAL ENERGY\s+(-?[\d.]+)\s*Eh", re.I)


def parse_xtb(text):
    """Pull the electronic properties out of an xtb run.

    Deliberately anchored on xtb's own labels — "(HOMO)", "(LUMO)", "HL-Gap" —
    rather than on line positions, which shift between versions and between
    single-point and optimisation runs.
    """
    out = {}

    m = _HOMO.search(text or "")
    if m:
        out["homo_eh"], out["homo_ev"] = float(m.group(1)), float(m.group(2))
    m = _LUMO.search(text or "")
    if m:
        out["lumo_eh"], out["lumo_ev"] = float(m.group(1)), float(m.group(2))

    m = _GAP.search(text or "")
    if m:
        out["gap_ev"] = float(m.group(2))
    elif "homo_ev" in out and "lumo_ev" in out:
        # derive rather than leave it missing, but only from values we parsed
        out["gap_ev"] = round(out["lumo_ev"] - out["homo_ev"], 4)

    m = _DIPOLE.search(text or "")
    if m:
        out["dipole_debye"] = float(m.group(1))
    m = _ENERGY.search(text or "")
    if m:
        out["total_energy_eh"] = float(m.group(1))

    # every occupied/virtual level, for the orbital diagram
    levels = []
    for line in (text or "").splitlines():
        mm = re.match(r"^\s*(\d+)\s+([\d.]+)?\s+(-?[\d.]+)\s+(-?[\d.]+)\s*(\(HOMO\)|\(LUMO\))?\s*$",
                      line)
        if mm:
            levels.append({
                "index": int(mm.group(1)),
                "occupation": float(mm.group(2)) if mm.group(2) else 0.0,
                "energy_ev": float(mm.group(4)),
                "label": (mm.group(5) or "").strip("()"),
            })
    if levels:
        out["levels"] = levels
    return out


def orbitals(smiles, timeout=180, charge=0):
    """HOMO, LUMO, gap and dipole for one molecule.

    Never raises: returns {"_error": ...} so a QM failure degrades this one
    panel rather than the analysis around it.
    """
    xtb = xtb_path()
    if not xtb:
        return {"_error": "The xtb quantum-chemistry engine is not installed "
                          "in this build."}
    try:
        xyz, n_atoms = prepare_xyz(smiles)
    except Exception as e:
        return {"_error": str(e)}

    with tempfile.TemporaryDirectory(prefix="mumo-qm-") as tmp:
        path = os.path.join(tmp, "mol.xyz")
        with open(path, "w", encoding="ascii") as fh:
            fh.write(xyz)
        cmd = [xtb, "mol.xyz", "--gfn", "2", "--sp", "--chrg", str(int(charge))]
        try:
            proc = subprocess.run(cmd, cwd=tmp, capture_output=True, text=True,
                                  timeout=timeout)
        except subprocess.TimeoutExpired:
            return {"_error": f"xtb did not finish within {timeout}s."}
        except Exception as e:
            return {"_error": f"Could not run xtb: {type(e).__name__}: {e}"}

        text = (proc.stdout or "") + "\n" + (proc.stderr or "")

    props = parse_xtb(text)
    if "homo_ev" not in props or "lumo_ev" not in props:
        # Refuse to invent numbers. A plausible-looking wrong HOMO/LUMO is
        # worse than none, because nothing downstream would catch it.
        tail = "\n".join(text.strip().splitlines()[-4:])
        return {"_error": "xtb ran but its output could not be parsed for "
                          f"HOMO/LUMO. Last lines: {tail[:200]}"}

    props["smiles"] = smiles
    props["n_atoms"] = n_atoms
    props["method"] = "GFN2-xTB (semi-empirical)"
    props["interpretation"] = _interpret(props)
    return props


def _interpret(p):
    """Plain-language reading of the numbers, in MUMO's beginner-first style.

    The gap is the useful one: it is the energy needed to promote an electron,
    so it tracks how readily a molecule takes part in electron transfer.
    """
    gap = p.get("gap_ev")
    if gap is None:
        return ""
    if gap < 2.0:
        band = ("a small gap — the molecule is easily polarised and readily "
                "takes part in electron transfer, which often tracks with "
                "chemical reactivity and sometimes with metabolic liability")
    elif gap < 4.5:
        band = ("a moderate gap — typical of drug-like aromatic compounds, "
                "stable but still able to engage in charge-transfer interactions")
    else:
        band = ("a large gap — electronically hard and relatively inert, which "
                "usually means good chemical stability")
    return (f"The HOMO sits at {p['homo_ev']:.2f} eV and the LUMO at "
            f"{p['lumo_ev']:.2f} eV, {gap:.2f} eV apart. That is {band}. "
            f"HOMO energy relates to how readily the molecule donates electron "
            f"density, LUMO to how readily it accepts it.")
